name: CI with MEGA Upload (Windows)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Download & Install MEGAcmd silently
      - name: Install MEGAcmd on Windows
        run: |
          Invoke-WebRequest -Uri "https://mega.nz/MEGAcmdSetup64.exe" -OutFile "MEGAcmdSetup64.exe"
          Start-Process .\MEGAcmdSetup64.exe -ArgumentList "/S" -Wait

      # Manually add MEGAcmd install folder to PATH
      - name: Add MEGAcmd to PATH
        run: |
          echo "C:\Users\runneradmin\AppData\Local\MEGAcmd" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      # Verify MEGAcmd is available
      - name: Verify MEGAcmd
        run: mega-version

      # Login to MEGA
      - name: MEGA Login
        env:
          MEGA_EMAIL: ${{ secrets.MEGA_EMAIL }}
          MEGA_PASSWORD: ${{ secrets.MEGA_PASSWORD }}
        run: mega-login "$env:MEGA_EMAIL" "$env:MEGA_PASSWORD"

      # Upload a file
      - name: Upload file to MEGA
        run: mega-put README.md /GitHubBackups/
